accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    
    path('signup/', signup, name='signup'),
    path('login/', login_check, name='login'),
    path('logout/', logout, name='logout'),
    
    path('follow/', follow, name='follow'),
    
    
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django.shortcuts import redirect


app_name = 'accounts'
urlpatterns = [
    
    
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    
    path('post/', include('post.urls', namespace='post')),
    path('', lambda r: redirect('post:post_list'), name='root')

    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    
    path('', post_list, name='post_list'),
    path('new', post_new, name='post_new'),
    path('edit/<int:pk>', post_edit, name='post_edit'),
    path('delete/<int:pk>', post_delete, name='post_delete'),
    path('like', post_like, name='post_like'),
    path('bookmark', post_bookmark, name='post_bookmark'),
    
    path('comment/new', comment_new, name='comment_new'),
    path('comment/delete', comment_delete, name='comment_delete'),
    path('explore/tags/<tag>/', post_list, name='post_search'),
    
    path('<int:pk>/', post_detail, name='post_detail'),
    
    path('<username>/list/detail', my_post_list, name='my_post_list'),
    
]

accounts/models.py
from django.conf import settings
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


def user_path(instance, filename):
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    extension = filename.split('.')[-1]
    return 'accounts/{}/{}.{}'.format(instance.user.username, pid, extension)



# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField('별명', max_length=20, unique=True)
    
    follow_set = models.ManyToManyField('self',
                                       blank=True,
                                       through='Follow',
                                       symmetrical=False,)
    
    picture = ProcessedImageField(upload_to=user_path,
                                  processors=[ResizeToFill(150, 150)],
                                  format='JPEG',
                                  options={'quality' : 90},
                                  blank=True,
                                 )
    about = models.CharField(max_length=300, blank=True)
    GENDER_C = (
        ('선택안함', '선택안함'),
        ('여성', '여성'),
        ('남성', '남성'),
    )
    gender = models.CharField('성별(선택사항)',
                            max_length=10,
                            choices=GENDER_C,
                            default='N')
    def __str__(self):
        return self.nickname
    
    @property
    def get_follower(self):
        return [i.from_user for i in self.follower_user.all()]
    
    @property
    def get_following(self):
        return [i.to_user for i in self.follow_user.all()]
    
    @property
    def follower_count(self):
        return len(self.get_follower)
    
    @property
    def following_count(self):
        return len(self.get_following)
    
    def is_follower(self, user):
        return user in self.get_follower
    
    def is_following(self, user):
        return user in self.get_following
    
    
    
class Follow(models.Model):
    from_user = models.ForeignKey(Profile, 
                                 related_name='follow_user',
                                 on_delete=models.CASCADE)
    
    to_user = models.ForeignKey(Profile, 
                               related_name='follower_user',
                               on_delete=models.CASCADE)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return "{} -> {}".format(self.from_user, self.to_user)
    
    class Meta:
        unique_together = (
            ('from_user', 'to_user')
        )

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "password"]
    
    
    
    
class SignupForm(UserCreationForm):
    username = forms.CharField(label='사용자명', widget=forms.TextInput(attrs={
        'pattern': '[a-zA-Z0-9]+',
        'title': '특수문자, 공백 입력불가',
    }))
    
    nickname = forms.CharField(label='닉네임')
    picture = forms.ImageField(label='프로필 사진', required=False)
    
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('email',)
        
    def clean_nickname(self):
        nickname = self.cleaned_data.get('nickname')
        if Profile.objects.filter(nickname=nickname).exists():
            raise forms.ValidationError('이미 존재하는 닉네임 입니다')
        return nickname
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        User = get_user_model()
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('사용중인 이메일 입니다.')
        return email
    
    def clean_picture(self):
        picture = self.cleaned_data.get('picture')
        if not picture:
            picture = None
        return picture
    
    def save(self):
        user = super().save()
        Profile.objects.create(
            user=user,
            nickname=self.cleaned_data['nickname'],
            picture=self.cleaned_data['picture'],
        )
        return user
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

accounts/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth import logout as django_logout
from .forms import SignupForm, LoginForm
from .models import Profile, Follow
import json
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            return redirect('accounts:login')
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {
        'form': form,
    })
            
    
    
def login_check(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        name = request.POST.get('username')
        pwd = request.POST.get('password')
        
        user = authenticate(username=name, password=pwd)
        
        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            return render(request, 'accounts/login_fail.html')
    else:
        form = LoginForm()
        return render(request, 'accounts/login.html', {'form':form})
    
def logout(request):
    django_logout(request)
    return redirect("/")



@login_required
@require_POST
def follow(request):
    from_user = request.user.profile
    pk = request.POST.get('pk')
    to_user = get_object_or_404(Profile, pk=pk)
    follow, created = Follow.objects.get_or_create(from_user=from_user, to_user=to_user)
    
    if created:
        message = '팔로우 시작'
        status = 1
    
    else:
        follow.delete()
        message = '팔로우 취소'
        status = 0
        
    context = {
        'message' : message,
        'status': status,
    }
    
    return HttpResponse(json.dumps(context), content_type="application/json")
        
                        

accounts/templates/accounts/layout.html
{% extends "layout.html" %}

accounts/templates/accounts/login.html
{% extends "accounts/layout.html" %}

{% block content %}



<div id="main_container">

        <div class="form_container">

            <div class="form">


                <h1 class="sprite_insta_big_logo title"></h1>

                <form method="POST" action="{% url 'accounts:login' %}">
					{% csrf_token %}
					
                    <p class="login_user_name">
                        <label for="id_user_name">사용자명:</label>
                        <input id="{{ form.user_name.id_for_label }}" maxlength="15" name="{{ form.user_name.html_name }}">
                    </p>

                    <p class="login_user_password">
                        <label for="id_user_password">비밀번호:</label>
                        <input id="{{ form.password.id_for_label }}" type="password" maxlength="15" name="{{ form.password.html_name }}">
                    </p>

                    <input type="submit" value="로그인" class="submit_btn">
                </form>



            </div>

            <div class="bottom_box">
                <div>
                    <span>아이디가 없으신가요?</span><a href="{% url 'accounts:signup' %}">회원가입</a>
                </div>
            </div>


        </div>

    </div>




{% endblock %}

accounts/templates/accounts/login_fail.html
{% extends "accounts/layout.html" %}

{% block content %}


<div id="main_container">

        <div class="form_container">

            <div class="form">


                <h1 class="sprite_insta_big_logo title">
                	
					로그인 실패
                </h1>
				<p>아이디가 없다면 회원가입 해주세요</p>

                



            </div>

            <div class="bottom_box">
                <div>
                    <span>아이디가 없으신가요?</span><a href="#">회원가입</a>
                </div>
            </div>


        </div>

    </div>


{% endblock %}

accounts/templates/accounts/signup.html
{% extends "accounts/layout.html" %}

{% block content %}


<div id="main_container">

        <div class="form_container">

            <div class="form">


                <form action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					
						{{ form.as_p }}
					<input class="submit_btn" type="submit" value="가입">
                   

                </form>



            </div>

            <div class="bottom_box">
                <div>
                    <span>아이디가 있다면</span><a href="">로그인</a>
                </div>
            </div>


        </div>

    </div>





{% endblock %}