accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    
    path('signup/', signup, name='signup'),
    path('login/', login_check, name='login'),
    path('logout/', logout, name='logout'),
    
    path('follow/', follow, name='follow'),
    
    
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django.shortcuts import redirect


app_name = 'accounts'
urlpatterns = [
    
    
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    
    path('post/', include('post.urls', namespace='post')),
    path('', lambda r: redirect('post:post_list'), name='root')

    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    
    path('', post_list, name='post_list'),
    path('new', post_new, name='post_new'),
    path('edit/<int:pk>', post_edit, name='post_edit'),
    path('delete/<int:pk>', post_delete, name='post_delete'),
    path('like', post_like, name='post_like'),
    path('bookmark', post_bookmark, name='post_bookmark'),
    
    path('comment/new', comment_new, name='comment_new'),
    path('comment/delete', comment_delete, name='comment_delete'),
    path('explore/tags/<tag>/', post_list, name='post_search'),
    
    path('<int:pk>/', post_detail, name='post_detail'),
    
    path('<username>/list/detail', my_post_list, name='my_post_list'),
    
]

post/models.py
from django.conf import settings
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import re

# Create your models here.

def photo_path(instance, filename):
    from time import strftime
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    extension = filename.split('.')[-1]
    return '{}/{}/{}.{}'.format(strftime('post/%Y/%m/%d/'), instance.author.username, pid, extension)

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = ProcessedImageField(upload_to=photo_path,
                               processors=[ResizeToFill(600, 600)],
                                format = 'JPEG',
                                options={'qualty':90})
    content = models.CharField(max_length=140, help_text="최대길이 140자 입력이 가능합니다.")

    tag_set = models.ManyToManyField('Tag', blank=True)
    
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL, 
                                          blank=True,
                                          related_name='like_user_set',
                                          through='Like') # post.like_set 으로 접근이 가능해진다.
    
    
    bookmark_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL, 
                                          blank=True,
                                          related_name='bookmark_user_set',
                                          through='Bookmark') # post.bookmark_set 으로 접근이 가능해진다.
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at']
        
    def tag_save(self):
        tags = re.findall(r'#(\w+)\b', self.content)
        
        if not tags:
            return
        
        for t in tags:
            tag, tag_created = Tag.objects.get_or_create(name=t)
            self.tag_set.add(tag)
    
        
    @property
    def like_count(self):
        return self.like_user_set.count()
    
    @property
    def bookmark_count(self):
        return self.bookmark_user_set.count()
    
    def __str__(self):
        return self.content
    
class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = (
            ('user', 'post')
        )
    
    

class Bookmark(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = (
            ('user', 'post')
        )
    
    
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-id']
        
    def __str__(self):
        return self.content
    
class Tag(models.Model):
    name = models.CharField(max_length=140, unique=True)
    
    def __str__(self):
        return self.name
    

post/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    photo = forms.ImageField(label='', required=False)
    content = forms.CharField(label='', widget=forms.Textarea(attrs={
        'class': 'post-new-content',
        'rows': 5,
        'cols': 50,
        'placeholder': '140자 까지 등록 가능합니다.'
    }))
    
    class Meta:
        model = Post
        fields = ['photo', 'content']
        
    

class CommentForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.TextInput(attrs={
        'class': 'comment-form',
        'size': '70px',
        'placeholder': '댓글 달기...',
        'maxlength': '40', }))
    
    class Meta:
        model = Comment
        fields = ['content']

post/views.py
import json
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from .forms import PostForm, CommentForm
from .models import Post, Like, Comment, Tag
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment_form = CommentForm()
    
    return render(request, 'post/post_detail.html', {
        'comment_form': comment_form,
        'post': post,
    })

def my_post_list(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    user_profile = user.profile
    
    target_user = get_user_model().objects.filter(id=user.id).select_related('profile') \
    .prefetch_related('profile__follower_user__from_user', 'profile__follow_user__to_user')
    
    post_list = user.post_set.all()
    all_post_list = Post.objects.all()
    return render(request, 'post/my_post_list.html', {
        'user_profile': user_profile,
        'target_user': target_user,
        'post_list': post_list,
        'all_post_list': all_post_list,
        'username': username,
    })


def post_list(request, tag=None):
    tag_all = Tag.objects.annotate(num_post=Count('post')).order_by('-num_post')
    
    if tag:
        post_list = Post.objects.filter(tag_set__name__iexact=tag) \
            .prefetch_related('tag_set', 'like_user_set__profile', 'comment_set__author__profile',
                              'author__profile__follower_user', 'author__profile__follower_user__from_user') \
            .select_related('author__profile')
    else:
        post_list = Post.objects.all() \
            .prefetch_related('tag_set', 'like_user_set__profile', 'comment_set__author__profile',
                              'author__profile__follower_user', 'author__profile__follower_user__from_user') \
            .select_related('author__profile')
    
    #post_list = Post.objects.all()
    
    comment_form = CommentForm()
    
    paginator = Paginator(post_list, 3)
    page_num = request.POST.get('page')
    
    try:
        posts = paginator.page(page_num)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
        
    if request.is_ajax():
        return render(request, 'post/post_list_ajax.html', {
            'posts': posts,
            'comment_form': comment_form,
        })
    
    if request.method == 'POST':
        tag = request.POST.get('tag')
        tag_clean = ''.join(e for e in tag if e.isalnum())
        return redirect('post:post_search', tag_clean)
    
    
    if request.user.is_authenticated:
        username = request.user
        user = get_object_or_404(get_user_model(), username=username)
        user_profile = user.profile
        
        following_set = request.user.profile.get_following
        following_post_list = Post.objects.filter(author__profile__in=following_set)
        
        return render(request, 'post/post_list.html', {
            'user_profile': user_profile,
            'tag': tag,
            'posts': posts,
            'comment_form': comment_form,
            'following_post_list': following_post_list,
            'tag_all': tag_all,
        })
    else:
        return render(request, 'post/post_list.html', {
            'tag': tag,
            'posts': posts,
            'comment_form': comment_form,
            'tag_all': tag_all,
        })

    
@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            post.tag_save()
            messages.info(request, '새 글이 등록되었습니다.')
            return redirect('post:post_list')
    else:
        form = PostForm()
    return render(request, 'post/post_new.html', {
        'form': form,
    })
        
    
@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user:
        messages.warning(request, '잘못된 접근입니다.')
        return redirect('post:post_list')
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            post.tag_set.clear()
            post.tag_save()
            messages.success(request, '수정완료')
            return redirect('post:post_list')
    else:
        form = PostForm(instance=post)
    return render(request, 'post/post_edit.html', {
        'post': post,
        'form': form,
    })
            
@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user or request.method == 'GET':
        messages.warning(request, '잘못된 접근입니다.')
        return redirect('post:post_list')
    
    if request.method == 'POST':
        post.delete()
        messages.success(request, '삭제완료')
        return redirect('post:post_list')
        
        
        



@login_required
@require_POST
def post_like(request):
    pk = request.POST.get('pk', None)
    post = get_object_or_404(Post, pk=pk)
    post_like, post_like_created = post.like_set.get_or_create(user=request.user)
    
    if not post_like_created:
        post_like.delete()
        message = "좋아요 취소"
    else:
        message = "좋아요"
    
    context = {'like_count': post.like_count,
              'message': message}
    
    return HttpResponse(json.dumps(context), content_type="application/json")
    
    
    
    
    
@login_required
@require_POST
def post_bookmark(request):
    pk = request.POST.get('pk', None)
    post = get_object_or_404(Post, pk=pk)
    post_bookmark, post_bookmark_created = post.bookmark_set.get_or_create(user=request.user)
    
    if not post_bookmark_created:
        post_bookmark.delete()
        message = "북마크 취소"
    else:
        message = "북마크"
    
    context = {'bookmark_count' : post.bookmark_count,
              'message': message}
    
    return HttpResponse(json.dumps(context), content_type="application/json")    
        
        
        
        
    
@login_required
def comment_new(request):
    pk = request.POST.get('pk')
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return render(request, 'post/comment_new_ajax.html', {
                'comment': comment,   
            })
    return redirect("post:post_list")



@login_required
def comment_delete(request):
    pk = request.POST.get('pk')
    comment = get_object_or_404(Comment, pk=pk)
    if request.method == 'POST' and request.user == comment.author:
        comment.delete()
        message = '삭제완료'
        status = 1
            
    else:
        message = '잘못된 접근입니다.'
        status = 0
            
    return HttpResponse(json.dumps({'message': message, 'status': status}), content_type="application/json")
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

post/templates/post/comment_new_ajax.html
<div class="comment-detail" id="comment{{ comment.id }}">
	<div class="nick_name m_text"> {{ comment.author.profile.nickname }}</div>
	<div>{{ comment.content }}</div>
	
	{% if user == comment.author %}
	<input type="button" class="del-comment" data-name="comment_delete" value="삭제" name="{{ comment.id }}">
	{% endif %}
	
</div>

post/templates/post/layout.html
{% extends "layout.html" %}

post/templates/post/post_list.html
{% extends "post/layout.html" %}
{% load static %}
{% load post_extras %}




{% block head %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/common.css' %}">
{% endblock %}





{% block content %}
<!-- hidden -->
{% if user.profile.get_following %}
<div class="hidden_menu">
	<div class="scroll_inner">
		{% for following in user.profile.get_following %}
		<div class="user">
			<div class="thumb_img">
				<img src="{{ following.picture.url }}" alt="">
			</div>
			<div class="id">{{ following.nickname }}</div>
		</div>
		{% endfor %}
	</div>
</div>

{% else %}

<div class="hidden_menu">
	<div class="scroll_inner">
		<div class="notic">
			팔로우한 유저가 없습니다. 팔로우를 해주세요.
		</div>
	</div>
</div>


{% endif %}





<!-- main -->
<section id="main_container">
        <div class="inner">
            <div class="contents_box">
				
				{% for post in posts %}
                <article class="contents">
                    <header class="top">
                        <div class="user_container">
                            <div class="profile_img">
								{% if post.author.profile.picture %}
                                <img src="{{ post.author.profile.picture.url }}" alt="프로필이미지">
								{% else %}
								<img src="{% static 'imgs/thumb.jpeg' %}" alt="프로필이미지">
								{% endif %}
                            </div>
                            <div class="user_name">
                                <div class="nick_name m_text">{{ post.author.profile.nickname }} {{ post.id }}</div>
                                <div class="country s_text">Seoul, South Korea</div>
                            </div>
							
							<div>
								<form action="{% url 'post:post_delete' post.pk %}" method="post">
									{% csrf_token %}
									<input type="submit" value="삭제">
								</form>
								
							</div>

                        </div>

                        <div class="sprite_more_icon" data-name="more">
                            <ul class="toggle_box">
                               <li>
								{% if user.profile in post.author.profile.get_follower %}
								   <input type="submit" class="follow" value="팔로잉" data-name="follow" name="{{ post.author.profile.id }}">
								{% else %}
								   <input type="submit" class="follow" value="팔로우" data-name="follow" name="{{ post.author.profile.id }}">
								{% endif %}
								</li>
								
								{% if post.author == user %}
                                <li>
									<a class="post-edit" href="{% url 'post:post_edit' post.pk %}">수정</a>
								</li>
                                <li>
									
									<form class="post-delete-form" action="{% url 'post:post_delete' post.pk %}" method="post">
										{% csrf_token %}
										<input type="submit" class="post-delete" value="삭제">
									</form>
								</li>
								{% endif %}]
                            </ul>
                        </div>
                    </header>

                    <div class="img_section">
                        <div class="trans_inner">
                            <div><img src="{{ post.photo.url }}" alt="visual01"></div>
                        </div>
                    </div>

                    <div class="bottom_icons">
                        <div class="left_icons">
                            <div class="heart_btn">
								{% if user in post.like_user_set.all %}
                                	<div class="sprite_heart_icon_outline on" name="{{ post.id }}" data-name="heartbeat"></div>
								{% else %}
									<div class="sprite_heart_icon_outline" name="{{ post.id }}" data-name="heartbeat"></div>
								{% endif %}
                            </div>
                            <a href="{% url 'post:post_detail' post.pk %}"><div class="sprite_bubble_icon"></div></a>
                            <div class="sprite_share_icon" data-name="share"></div>
                        </div>
                        <div class="right_icon">
							{% if user in post.bookmark_user_set.all %}
                            	<div class="sprite_bookmark_outline on" name="{{ post.id }}" data-name="bookmark"></div>
							{% else %}
								<div class="sprite_bookmark_outline" name="{{ post.id }}" data-name="bookmark"></div>
							{% endif %}
                        </div>
                    </div>

                    <div class="likes m_text">
                        
                        <span id="like-count-{{ post.id }}">좋아요{{ post.like_count }}개</span>
                        <span id="bookmark-count-{{ post.id }}">북마크{{ post.bookmark_count }}개</span>
                        
                    </div>
					
					<div class="content">{{ post | add_link | safe | linebreaksbr }}</div>

                    <div class="comment_container">
                        <div class="comment" id="comment-list-ajax-post{{post.id}}">
							{% for comment in post.comment_set.all %}
                            <div class="comment-detail" id="comment{{ comment.id }}">
                                <div class="nick_name m_text">{{ comment.author.profile.nickname }}</div>
									<div>{{ comment.content }}</div>
								{% if user == comment.author %}
									<input type="button" class="del-comment" data-name="comment_delete" value="삭제" name="{{ comment.id }}">
								{% endif %}
                                
                            </div>
							{% endfor %}
                        </div>
                        <div class="small_heart">
                            <div class="sprite_small_heart_icon_outline"></div>
                        </div>
                    </div>

                    <div class="timer">{{ post.created_at|timesince }} 전</div>

                    <div class="comment_field" id="add-comment-post{{post.id}}">
						{% if user.is_authenticated %}
						{{ comment_form }}
						
						
                        <div class="upload_btn m_text" name="{{post.id}}" data-name="comment">게시</div>
						{% else %}
						{{ comment_form }}
						
                        <div class="upload_btn m_text" name="{{post.id}}" data-name="comment" onclick="alert('댓글을 작성하려면 로그인이 필요합니다')">게시</div>
						
						{% endif %}
                    </div>
                </article>
				{% endfor %}

				<div id="post_list_ajax"></div>
				<input type="hidden" id="page" value="2">
            </div>
            

            <div class="side_box">
				{% if user_profile %}
                <div class="user_profile">
                    <div class="profile_thumb">
                        <img src="{{ user_profile.picture.url }}" alt="프로필사진">
                    </div>
                    <div class="detail">
                        <div class="id m_text">{{ user_profile.user }}</div>
                        <div class="ko_name">{{ user_profile.nickname }}</div>
                    </div>
                </div>
				{% else %}
				
				<div class="user_profile">
                    <div class="profile_thumb">
                        <img src="{% static 'imgs/thumb.jpeg' %}" alt="프로필사진">
                    </div>
                    <div class="detail">
                    </div>
                </div>
				
				{% endif %}

                <article class="story">
                    <header class="story_header">
                        <div>스토리</div>
                        <div class="more">모두 보기</div>
                    </header>

                    <div class="scroll_inner">
						{% if following_post_list %}
						{% for post in following_post_list %}
                        <div class="thumb_user">
                            <div class="profile_thumb">
                                <img src="{{ post.photo.url }}" alt="프로필사진">
                            </div>
                            <div class="detail">
                                <div class="id">{{ post.content }}</div>
                                <div class="time">{{ post.updated_at|timesince }}</div>
                            </div>
                        </div>
						{% endfor %}
						{% endif %}
                    </div>
                </article>

                <article class="recommend">
                    <header class="reco_header">
                        <div>회원님을 위한 추천</div>
                        <div class="more">모두 보기</div>
                    </header>
					{% for post in posts|slice:"2:3" %}
                    <div class="thumb_user">
                        <div class="profile_thumb">
                            <img src="{{ post.photo.url }}" alt="프로필사진">
                        </div>
                        <div class="detail">
                            <div class="id">{{ post.content }}</div>
                            <div class="time">{{ post.updated_at|timesince }}</div>
                        </div>
                    </div>
					{% endfor %}
                </article>
            </div>


        </div>
    </section>

{% include "post/script_ajax.html" %}

{% endblock %}

post/templates/post/script_ajax.html
<script type="text/javascript">
(function(){
	const delegation = document.querySelector('.contents_box');
	const side_box = document.querySelector('.side_box');
	const header = document.querySelector('#header');
	
	function delegationFunc(e){
		let elem = e.target;
		
		console.log(elem);
		
		while(!elem.getAttribute('data-name')){
			elem = elem.parentNode;
			
			if(elem.nodeName === 'BODY'){
				elem = null;
				return;
			}
		}
		
		if(elem.matches('[data-name="heartbeat"]')){
			console.log('하트');
			
			var pk = elem.getAttribute('name');
			console.log(pk);
			
			$.ajax({
				type: "POST",
				url: "{% url 'post:post_like' %}",
				data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
				dataType: "json",
				success: function (response){
					//alert('성공');
					var likeCount = document.querySelector('#like-count-'+pk);
					likeCount.innerHTML = '좋아요' + response.like_count + '개';
				},
				error: function(request, status, error){
					alert("code:" + request.status+"\n" + "message:"+request.responseText+"\n"+"error:"+error);
				},
			});
			
			
		} else if(elem.matches('[data-name="bookmark"]')){
			console.log('북마크');
			
			var pk = elem.getAttribute('name');
			console.log(pk);
			
			$.ajax({
				type: "POST",
				url: "{% url 'post:post_bookmark' %}",
				data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
				dataType: "json",
				success: function (response){
					//alert('성공');
					var likeCount = document.querySelector('#bookmark-count-'+pk);
					likeCount.innerHTML = '북마크' + response.bookmark_count + '개';
				},
				error: function(request, status, error){
					alert("code:" + request.status+"\n" + "message:"+request.responseText+"\n"+"error:"+error);
				},
			});
		} else if (elem.matches('[data-name="comment"]')){
			console.log('새댓글')
			var pk = elem.getAttribute('name');
			var content = document.querySelector('#add-comment-post'+pk+'>input[type=text]').value;
			console.log(content);
			
			if(content.length > 140) {
				alert("댓글은 최대 140자 입력 가능합니다. 현재 글자수 : " + content.length);
				return;
			}
			
			$.ajax({
				type: "POST",
				url: "{% url 'post:comment_new' %}",
				data: {
					'pk': pk,
                    'content': content,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
				},
				dataType: "html",
				success: function(data, textStatus, jqXHR){
					console.log("성공");
					document.querySelector("#comment-list-ajax-post"+pk).insertAdjacentHTML("afterbegin", data);
				},
				error: function(request, status, error){
					alert("code:" + request.status+"\n" + "message:"+request.responseText+"\n"+"error:"+error);
				},
				
			});
		}else if(elem.matches('[data-name="comment_delete"]')){
			var pk = elem.getAttribute('name');
			
			$.ajax({
				type: "POST",
				url: "{% url 'post:comment_delete' %}",
				data: {
					'pk': pk,
					'csrfmiddlewaretoken': '{{ csrf_token }}',
				},
				dataType: "json",
				success: function(response){
					if(response.status){
						document.querySelector('#comment'+pk).remove();
					}
				},
				error: function(request, status, error){
					alert("code:" + request.status+"\n" + "message:"+request.responseText+"\n"+"error:"+error);
				}
				
			});
			
		}else if(elem.matches('[data-name="follow"]')){
			console.log('팔로우');
			var pk = elem.getAttribute('name');
			
			$.ajax({
				type: "POST",
				url: "{% url 'accounts:follow' %}",
				data: {
					'pk': pk,
					'csrfmiddlewaretoken': '{{ csrf_token }}',
				},
				dataType: "json",
				success: function(response){
					console.log("성공");
					
					if(response.status){
						document.querySelector('input.follow[name=\''+pk+'\']').value = "팔로잉";
					} else {
						document.querySelector('input.follow[name=\''+pk+'\']').value = "팔로우";
					}
					
					
				},
				error: function(request, status, error){
					alert("code:" + request.status+"\n" + "message:"+request.responseText+"\n"+"error:"+error);
				}
			});
		}
		
		elem.classList.toggle('on');
	}
	
	
	function resizefunc(){
		console.log('리사이즈');
		if(pageYOffset >= 10){
			let calcWidth = (window.innerWidth * 0.5) + 167;
			if(side_box){
				side_box.style.left = calcWidth + "px";
			}
		}
	}
	
	
	function scrollfunc(){
		var scrollHeight = pageYOffset + window.innerHeight;
		var documentHeight = document.body.scrollHeight;
		
		console.log(pageYOffset);
		console.log('scrollHeight: ' + scrollHeight);
		console.log('documentHeight: ' + documentHeight);
		
		if(pageYOffset >= 10) {
			header.classList.add('on');
			resizefunc();
			if(side_box){
				side_box.classList.add('on');
			}
		} else {
			header.classList.remove('on');
			if(side_box){
				side_box.classList.remove('on');
				side_box.removeAttribute('style');
			}
		}
		
		if(scrollHeight >= documentHeight) {
			var page = document.querySelector('#page').value;
			var end_page = {{ posts.paginator.num_pages }};
			if(page > end_page){
				return;
			}
			document.querySelector('#page').value = parseInt(page) + 1;
			callMorePostAjax(page);
		}
	}
	
 	function callMorePostAjax(page){
		var end_page = {{ posts.paginator.num_pages }};
		if(page > end_page){
			return;
		}
		$.ajax({
			type: 'POST',
			url: "{% url 'post:post_list' %}",
			data: {
				'page':page,
				'csrfmiddlewaretoken': '{{ csrf_token }}',
			},
			dataType: 'html',
			success: addMorePostAjax,
			error: function(request, status, error){
				alert("code:" + request.status+"\n" + "message:"+request.responseText+"\n"+"error:"+error);
			}
		});
	}
	
	function addMorePostAjax(data, textStatus, jqXHR){
		let post = document.querySelector('#post_list_ajax');
		post.insertAdjacentHTML("beforeend", data);
	}

	
	window.addEventListener('resize', resizefunc);
	window.addEventListener('scroll', scrollfunc);
	delegation.addEventListener('click', delegationFunc);
})();
	
	
	

</script>

post/templates/post/script_ajax_detail.html
<script type="text/javascript">

(function(){
	
	const delegation = document.querySelector('.contents_box');
	
	
	function delegationFunc(e) {
		let elem = e.target;
		
		while(!elem.getAttribute('data-name')){
			elem = elem.parentNode;
			
			if(elem.nodeName === 'BODY'){
				elem = null;
				return;
			}

		}
		if (elem.matches('[data-name="follow"]')){
			console.log('팔로우');
			var pk = elem.getAttribute('name');
				
			$.ajax({
			type: "POST",
			url: "{% url 'accounts:follow' %}",
			data: {
				'pk': pk,
				'csrfmiddlewaretoken': '{{ csrf_token }}',
			},
			dataType: "json",
			success: function(response){
				console.log("성공");
				
				if(response.status){
					document.querySelector('input.follow[name=\''+pk+'\']').value = "팔로잉";
				} else {
					document.querySelector('input.follow[name=\''+pk+'\']').value = "팔로우";
				}
				
				
			},
			error: function(request, status, error){
				alert("code:" + request.status+"\n" + "message:"+request.responseText+"\n"+"error:"+error);
			}
			});
		}else if(elem.matches('[data-name="heartbeat"]')){
			console.log('하트');
			
			var pk = elem.getAttribute('name');
			console.log(pk);
			
			$.ajax({
				type: "POST",
				url: "{% url 'post:post_like' %}",
				data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
				dataType: "json",
				success: function (response){
					//alert('성공');
					var likeCount = document.querySelector('#like-count-'+pk);
					likeCount.innerHTML = '좋아요' + response.like_count + '개';
				},
				error: function(request, status, error){
					alert("code:" + request.status+"\n" + "message:"+request.responseText+"\n"+"error:"+error);
				},
			});
			
			
		}else if(elem.matches('[data-name="bookmark"]')){
			console.log('북마크');
			
			var pk = elem.getAttribute('name');
			console.log(pk);
			
			$.ajax({
				type: "POST",
				url: "{% url 'post:post_bookmark' %}",
				data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
				dataType: "json",
				success: function (response){
					//alert('성공');
					var likeCount = document.querySelector('#bookmark-count-'+pk);
					likeCount.innerHTML = '북마크' + response.bookmark_count + '개';
				},
				error: function(request, status, error){
					alert("code:" + request.status+"\n" + "message:"+request.responseText+"\n"+"error:"+error);
				},
			});
		}
		
		elem.classList.toggle('on');
	}
	
	
	delegation.addEventListener('click', delegationFunc);
})();
</script>