accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    
    path('signup/', signup, name='signup'),
    path('login/', login_check, name='login'),
    path('logout/', logout, name='logout'),
    
    path('follow/', follow, name='follow'),
    
    
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django.shortcuts import redirect


app_name = 'accounts'
urlpatterns = [
    
    
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    
    path('post/', include('post.urls', namespace='post')),
    path('', lambda r: redirect('post:post_list'), name='root')

    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    
    path('', post_list, name='post_list'),
    path('new', post_new, name='post_new'),
    path('edit/<int:pk>', post_edit, name='post_edit'),
    path('delete/<int:pk>', post_delete, name='post_delete'),
    path('like', post_like, name='post_like'),
    path('bookmark', post_bookmark, name='post_bookmark'),
    
    path('comment/new', comment_new, name='comment_new'),
    path('comment/delete', comment_delete, name='comment_delete'),
    path('explore/tags/<tag>/', post_list, name='post_search'),
    
    path('<int:pk>/', post_detail, name='post_detail'),
    
    path('<username>/list/detail', my_post_list, name='my_post_list'),
    
]

config/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	
	<link rel="stylesheet" href="{% static 'css/common.css' %}">
	<link rel="stylesheet" href="{% static 'css/reset.css' %}">
	
	<!--<link rel="stylesheet" href="{% static 'css/detail-page.css' %}">
	<link rel="stylesheet" href="{% static 'css/login.css' %}">
	<link rel="stylesheet" href="{% static 'css/mylist.css' %}">
	<link rel="stylesheet" href="{% static 'css/new_post.css' %}">
	<link rel="stylesheet" href="{% static 'css/profile.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">-->
	
	<!--<script src="{% static 'js/profile.js' %}"></script>-->
	
	{% block head %}
	{% endblock %}
	
</head>
<body>
	<section id="container">
		<header id="header">
			<section class="h_inner">
				<h1 class="logo">
                <a href="{% url 'post:post_list' %}">
                    <div class="sprite_insta_icon"></div>
                    <div>
                        <div class="sprite_write_logo"></div>
                    </div>
                </a>
            </h1>
				<div class="search_field">
					<input type="text" placeholder="검색" tabindex="0">
					<div class="fake_field">
						<span class="sprite_small_search_icon"></span>
						<span>검색</span>
					</div>
				</div>
				<div class="right_icons">
					<div class="sprite_camera_icon"><a href="{% url 'post:post_new' %}"></a></div>
                	<div class="sprite_compass_icon"><a href="#"></a></div>
                	<div class="sprite_heart_icon_outline"><a href="follow.html"></a></div>
					{% if user.is_authenticated %}
                
                <div class="sprite_user_icon_outline"><a href="{% url 'post:my_post_list' user.username %}"></a></div>
                
                {% else %}
                
                <div class="sprite_user_icon_outline"><a href="{% url 'accounts:login' %}"></a></div>
                
                {% endif %}
				</div>
				
			</section>
		</header>
		
		{% block content %}
		{% endblock %}
		
	</section>
	
	<!-- jQuery (부트스트랩의 자바스크립트 플러그인을 위해 필요합니다) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- <script src="{% static 'js/insta.js' %}"></script> -->
    {% block js %}
    {% endblock %} 
</body>
</html>